'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const query=require('../server/discovery/query'); const {DatabaseClient}=require('../server/db/client');
const rows=[
 {id:'a',source:'servicelink',state:'CA',county:'Los Angeles',address:'1 Main St',propType:'Land',status:'active',lat:34,lng:-118,openingBid:10,dealScore:90,sourceObservedAt:'2026-09-05T00:00:00Z',provenance:{origin:'live',recordId:'p1',sourceFacts:{auctionProgram:'TPS'}}},
 {id:'b',source:'hud',state:'FL',county:null,address:'2 Palm St',propType:'Single Family',status:'scheduled',lat:25,lng:179,openingBid:null,dealScore:null,sourceObservedAt:'2026-09-05T00:00:00Z',provenance:{origin:'live',recordId:'p2'}}
];
const db={getListings:async()=>({total:rows.length,listings:rows})};
function url(q=''){return new URL(`http://local/api/listings?${q}`);}
test('discovery search returns facets and a revision-bound cursor',async()=>{const first=await query.search(db,query.queryFromUrl(url('limit=1&facets=state,program')));assert.equal(first.listings.length,1);assert.equal(first.page.hasMore,true);assert.deepEqual(first.facets.program,[{value:'TPS',count:1},{value:'unknown',count:1}]);const next=await query.search(db,query.queryFromUrl(url(`limit=1&facets=state,program&cursor=${first.page.nextCursor}`)));assert.equal(next.listings[0].id,'b');await assert.rejects(()=>query.search(db,query.queryFromUrl(url(`limit=1&state=CA&cursor=${first.page.nextCursor}`))),/does not match/);});
test('bbox accepts antimeridian crossing and map stays minimal',async()=>{const f=query.queryFromUrl(url('bbox=170,-10,-170,40&limit=100'));const result=await query.map(db,f);assert.deepEqual(result.features.map(x=>x.properties.id),['b']);assert.deepEqual(Object.keys(result.features[0].properties).sort(),['count','id','source','status']);});
test('invalid geographic and boolean parameters fail closed',()=>{assert.throws(()=>query.queryFromUrl(url('bbox=-181,0,1,2')),/Invalid bbox/);assert.throws(()=>query.queryFromUrl(url('hasDocuments=yes')),/true or false/);});
test('advanced mode requires PostgreSQL configuration',()=>{assert.throws(()=>new DatabaseClient({env:{DISCOVERY_MODE:'advanced',NODE_ENV:'test'}}),/requires DATABASE_URL/);});
test('PostgreSQL discovery filters and paginates in SQL without loading inventory',async()=>{const calls=[];const database={isPg:true,listingSelect:'id, source_key AS "source", state, address, updated_at AS "fetchedAt"',pool:{query:async(sql,params=[])=>{calls.push({sql,params});if(sql.includes('md5('))return{rows:[{revision:'rev'}]};if(sql.includes('count(*)::int'))return{rows:[{count:1}]};return{rows:[{id:'pg1',source:'hud',state:'CA',address:'1 SQL Way',cursorValue:7}]};}}};const result=await query.search(database,query.queryFromUrl(url('state=CA&program=tps&limit=25')));assert.equal(result.total,1);assert.equal(result.listings[0].id,'pg1');assert.match(calls[1].sql,/state=\$1/);assert.match(calls[1].sql,/lower\(auction_program\)=\$2/);assert.match(calls[1].sql,/ORDER BY/);});
