// AUTO-GENERATED by scripts/build-data.js — do not edit by hand.
// Run `node scripts/build-data.js` to regenerate from server/scrapers/.
// Last generated: 2026-08-31T22:52:57.940Z
// SOURCES taxonomy kept in sync with src/components/terminal/property-data.ts
// via test/sync.test.js.

window.SOURCES = {
  "sheriff": {
    "key": "sheriff",
    "label": "Sheriff Sale",
    "tier": "B",
    "color": "#0f766e",
    "note": "Foreclosure sale notice published under state law",
    "websiteUrl": "https://www.cuyahogasheriff.org"
  },
  "trustee": {
    "key": "trustee",
    "label": "Trustee's Sale",
    "tier": "B",
    "color": "#0ea5e9",
    "note": "Non-judicial foreclosure auction",
    "websiteUrl": "https://www.clarkcountynv.gov"
  },
  "hud": {
    "key": "hud",
    "label": "HUD Home",
    "tier": "A",
    "color": "#1d4ed8",
    "note": "hudhomestore.gov — owner-occupant window applies",
    "websiteUrl": "https://www.hudhomestore.gov"
  },
  "fannie": {
    "key": "fannie",
    "label": "Fannie Mae REO",
    "tier": "A",
    "color": "#2563eb",
    "note": "homepath.com — First Look window",
    "websiteUrl": "https://www.homepath.com"
  },
  "freddie": {
    "key": "freddie",
    "label": "Freddie Mac REO",
    "tier": "A",
    "color": "#1e40af",
    "note": "homesteps.com",
    "websiteUrl": "https://www.homesteps.com"
  },
  "usda": {
    "key": "usda",
    "label": "USDA RD/FSA REO",
    "tier": "A",
    "color": "#3b82f6",
    "note": "resales.usda.gov",
    "websiteUrl": "https://www.resales.usda.gov"
  },
  "va": {
    "key": "va",
    "label": "VA REO",
    "tier": "A",
    "color": "#0e7490",
    "note": "vrmproperties.com",
    "websiteUrl": "https://vrmproperties.com"
  },
  "irs": {
    "key": "irs",
    "label": "IRS Seized",
    "tier": "A",
    "color": "#b45309",
    "note": "irsauctions.gov — email subscribe",
    "websiteUrl": "https://www.irsauctions.gov"
  },
  "treasury": {
    "key": "treasury",
    "label": "Treasury Forfeiture",
    "tier": "A",
    "color": "#c2410c",
    "note": "CWS Marketing contractor",
    "websiteUrl": "https://www.treasury.gov/auctions/treasury/rp/realprop.shtml"
  },
  "marshals": {
    "key": "marshals",
    "label": "US Marshals",
    "tier": "A",
    "color": "#a16207",
    "note": "RealLook.com / Gaston & Sheehan",
    "websiteUrl": "https://www.usmarshals.gov"
  },
  "gsa": {
    "key": "gsa",
    "label": "GSA Surplus",
    "tier": "A",
    "color": "#92400e",
    "note": "realestatesales.gov",
    "websiteUrl": "https://realestatesales.gov"
  }
};

window.LISTINGS = [];
