import { BookOpen, ExternalLink, Layers3 } from "lucide-react";
import { sourceDisplayText } from "@/lib/source-display";

export type AtlasSource = { id: string; label: string; urls?: string[]; access?: string; authorStatus?: string; automationStatus?: string; evidenceClass?: string };
export type SourceAtlasData = { sources: AtlasSource[]; total: number; ledgerRows?: number; unmappedLedgerRows?: number };

export function SourceAtlas({ atlas, storageMode }: { atlas?: SourceAtlasData; storageMode?: string }) {
  if (!atlas) return null;
  return <section className="mt-9 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7" aria-labelledby="source-atlas-heading">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.15em] text-emerald-700"><Layers3 size={16} />Source coverage atlas</p><h2 id="source-atlas-heading" className="mt-2 text-2xl font-semibold">Documented coverage backlog</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">These source references are document claims awaiting authorization and evidence review. A catalog row does not indicate a live collector, access approval, or property availability.</p></div><div className="rounded-xl bg-slate-50 px-4 py-3 text-right text-xs"><p className="font-bold">{atlas.total} source references</p><p className="mt-1 text-slate-500">{atlas.ledgerRows ?? 0} ledger rows · {atlas.unmappedLedgerRows ?? 0} unmapped</p>{storageMode ? <p className="mt-1 text-slate-500">{storageMode}</p> : null}</div></div>
    <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{atlas.sources.map((source) => <article key={source.id} className="rounded-xl border border-slate-200 p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-900">{source.evidenceClass?.replaceAll("_", " ") || "Document claim"}</p><h3 className="mt-2 font-semibold">{sourceDisplayText(source.label)}</h3><dl className="mt-3 space-y-1 text-xs text-slate-600"><div className="flex justify-between gap-3"><dt>Access</dt><dd className="text-right font-medium">{source.access || "Not established"}</dd></div><div className="flex justify-between gap-3"><dt>Authorization</dt><dd className="text-right font-medium">{source.authorStatus || "Pending review"}</dd></div><div className="flex justify-between gap-3"><dt>Automation</dt><dd className="text-right font-medium">{source.automationStatus || "Backlog"}</dd></div></dl>{source.urls?.[0] ? <a href={source.urls[0]} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-slate-900 underline hover:text-slate-700">Reference <ExternalLink size={12} /></a> : <p className="mt-4 flex items-center gap-1 text-xs text-slate-500"><BookOpen size={12} />No public reference URL captured</p>}</article>)}</div>
    {!atlas.sources.length && <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">No source-atlas entries have been loaded.</p>}
  </section>;
}
