'use strict';
const crypto=require('node:crypto');
const {canonicalJson}=require('../intelligence/hunts');
const digest=v=>crypto.createHash('sha256').update(canonicalJson(v)).digest('hex');
class PgHuntStore{
 constructor(pool){if(!pool?.query)throw new Error('Durable hunts require PostgreSQL');this.pool=pool;}
 async list(){return (await this.pool.query('SELECT id,name,enabled,version,criteria,criteria_hash AS "criteriaHash",created_at AS "createdAt",updated_at AS "updatedAt" FROM discovery_hunts ORDER BY updated_at DESC')).rows;}
 async get(id){const r=await this.pool.query('SELECT id,name,enabled,version,criteria,criteria_hash AS "criteriaHash",created_at AS "createdAt",updated_at AS "updatedAt" FROM discovery_hunts WHERE id=$1',[id]);return r.rows[0]||null;}
 async create(value){const id=`hunt_${crypto.randomBytes(12).toString('hex')}`,criteriaHash=digest(value.criteria);const r=await this.pool.query('INSERT INTO discovery_hunts(id,name,enabled,criteria,criteria_hash) VALUES($1,$2,$3,$4,$5) RETURNING id,name,enabled,version,criteria,criteria_hash AS "criteriaHash",created_at AS "createdAt",updated_at AS "updatedAt"',[id,value.name,value.enabled, value.criteria,criteriaHash]);return r.rows[0];}
 async update(id,value){const current=await this.get(id);if(!current)return null;const criteria=value.criteria||current.criteria,changed=canonicalJson(criteria)!==canonicalJson(current.criteria);const r=await this.pool.query('UPDATE discovery_hunts SET name=$2,enabled=$3,criteria=$4,criteria_hash=$5,version=version+$6,updated_at=NOW() WHERE id=$1 RETURNING id,name,enabled,version,criteria,criteria_hash AS "criteriaHash",created_at AS "createdAt",updated_at AS "updatedAt"',[id,value.name??current.name,value.enabled??current.enabled,criteria,digest(criteria),changed?1:0]);return r.rows[0];}
 async delete(id){return (await this.pool.query('DELETE FROM discovery_hunts WHERE id=$1 RETURNING id',[id])).rows[0]||null;}
 async baseline(id){const rows=(await this.pool.query('SELECT identity_key,source_key,source_record_id,observed_at,evaluation,hunt_version FROM discovery_hunt_baselines WHERE hunt_id=$1',[id])).rows;return rows.length?{huntVersion:rows[0].hunt_version,records:Object.fromEntries(rows.map(r=>[r.identity_key,r.evaluation]))}:null;}
 async saveEvaluation(hunt,evaluated){const c=await this.pool.connect();try{await c.query('BEGIN');for(const [key,r] of Object.entries(evaluated.baseline.records))await c.query('INSERT INTO discovery_hunt_baselines(hunt_id,identity_key,hunt_version,source_key,source_record_id,observed_at,evaluation) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(hunt_id,identity_key) DO UPDATE SET hunt_version=EXCLUDED.hunt_version,source_key=EXCLUDED.source_key,source_record_id=EXCLUDED.source_record_id,observed_at=EXCLUDED.observed_at,evaluation=EXCLUDED.evaluation WHERE discovery_hunt_baselines.observed_at<=EXCLUDED.observed_at',[hunt.id,key,evaluated.baseline.huntVersion,r.sourceId,r.recordId,r.observedAt,r]);for(const e of evaluated.events)await c.query('INSERT INTO discovery_hunt_events(id,hunt_id,identity_key,event_type,evidence,detected_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO NOTHING',[e.id,hunt.id,e.identityKey,e.type,e,e.detectedAt]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}return evaluated.response;}
 async events(id,limit=50){return (await this.pool.query('SELECT evidence FROM discovery_hunt_events WHERE hunt_id=$1 ORDER BY detected_at DESC LIMIT $2',[id,Math.max(1,Math.min(200,limit))])).rows.map(r=>r.evidence);}
}
module.exports={PgHuntStore,createPgHuntStore:db=>new PgHuntStore(db.pool||db)};
