'use strict';
const crypto = require('node:crypto');

function stable(value) { if (Array.isArray(value)) return value.map(stable); if (value && typeof value === 'object') return Object.fromEntries(Object.keys(value).sort().map(k => [k, stable(value[k])])); return value; }
function hash(value) { return crypto.createHash('sha256').update(JSON.stringify(stable(value))).digest('hex'); }
function collectionJobId(){return `job_${crypto.randomBytes(12).toString('hex')}`;}
function jsonValue(value,fallback){if(value==null)return fallback;if(typeof value==='string'){try{return JSON.parse(value);}catch{return fallback;}}return value;}
function requirePool(pool) { if (!pool?.query) throw new Error('Discovery persistence requires PostgreSQL'); return pool; }

class DiscoveryStore {
  constructor(pool) { this.pool = requirePool(pool); }
  async beginRun({ sourceKey, trigger = 'manual', scope = {}, idempotencyKey = null }) {
    const scopeHash = hash(scope); const r = await this.pool.query("INSERT INTO discovery_source_runs(source_key,trigger,scope,scope_hash,status,idempotency_key) VALUES($1,$2,$3,$4,'running',$5) ON CONFLICT(source_key,idempotency_key) WHERE idempotency_key IS NOT NULL DO UPDATE SET source_key=EXCLUDED.source_key RETURNING *", [sourceKey, trigger, scope, scopeHash, idempotencyKey]); return r.rows[0];
  }
  async appendSnapshot({ runId, sourceKey, sourceRecordId, observedAt, rawPayload, provenance = {}, observations = {} }, options = {}) {
    const payloadSha256 = hash(rawPayload); const client = options.client || await this.pool.connect(); const ownsTransaction=!options.client;
    try { if(ownsTransaction) await client.query('BEGIN'); let r = await client.query('INSERT INTO discovery_snapshots(run_id,source_key,source_record_id,observed_at,payload_sha256,raw_payload,provenance) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(source_key,source_record_id,observed_at,payload_sha256) DO NOTHING RETURNING *', [runId,sourceKey,sourceRecordId,observedAt,payloadSha256,rawPayload,provenance]);
      if (!r.rows[0]) r=await client.query('SELECT * FROM discovery_snapshots WHERE source_key=$1 AND source_record_id=$2 AND observed_at=$3 AND payload_sha256=$4',[sourceKey,sourceRecordId,observedAt,payloadSha256]);
      for (const [field,item] of Object.entries(observations)) { const wrapped=item&&typeof item==='object'&&!Array.isArray(item)&&Object.hasOwn(item,'value'); const value=wrapped?item.value:item; const evidenceClass=wrapped&&item.evidenceClass?item.evidenceClass:'publisher_reported'; await client.query('INSERT INTO discovery_observations(snapshot_id,field_name,value,evidence_class) VALUES($1,$2,$3,$4) ON CONFLICT(snapshot_id,field_name) DO NOTHING', [r.rows[0].id,field,JSON.stringify(value===undefined?null:value),evidenceClass]); }
      if(ownsTransaction) await client.query('COMMIT'); return r.rows[0]; } catch(e){ if(ownsTransaction) await client.query('ROLLBACK'); throw e; } finally { if(ownsTransaction) client.release(); }
  }
  async finishRun(id, result) { const status = ['complete','partial','failed'].includes(result.status) ? result.status : 'failed'; const r=await this.pool.query('UPDATE discovery_source_runs SET status=$2,completed_at=NOW(),discovered_count=$3,accepted_count=$4,rejected_count=$5,error_message=$6 WHERE id=$1 RETURNING *',[id,status,result.discovered||0,result.accepted||0,result.rejected||0,result.error?String(result.error).slice(0,500):null]); return r.rows[0]; }
  async ingestSnapshot(input, projector) { const client=await this.pool.connect(); try { await client.query('BEGIN'); const snapshot=await this.appendSnapshot(input,{client}); if(typeof projector==='function') await projector(client,snapshot); await client.query('COMMIT'); return snapshot; } catch(e){await client.query('ROLLBACK');throw e;} finally{client.release();} }
  async getCheckpoint(sourceKey) { const r=await this.pool.query('SELECT cursor,scope_hash AS "scopeHash",updated_at AS "updatedAt" FROM discovery_checkpoints WHERE source_key=$1',[sourceKey]); return r.rows[0]||null; }
  async saveCheckpoint(sourceKey, cursor, scope = {}) { const r=await this.pool.query('INSERT INTO discovery_checkpoints(source_key,cursor,scope_hash) VALUES($1,$2,$3) ON CONFLICT(source_key) DO UPDATE SET cursor=EXCLUDED.cursor,scope_hash=EXCLUDED.scope_hash,updated_at=NOW() RETURNING *',[sourceKey,cursor,hash(scope)]); return r.rows[0]; }
  async acquireLease(key, ownerId, ttlSeconds=300) { const r=await this.pool.query("INSERT INTO discovery_leases(lease_key,owner_id,expires_at) VALUES($1,$2,NOW()+make_interval(secs=>$3)) ON CONFLICT(lease_key) DO UPDATE SET owner_id=EXCLUDED.owner_id,expires_at=EXCLUDED.expires_at,updated_at=NOW() WHERE discovery_leases.expires_at<NOW() OR discovery_leases.owner_id=EXCLUDED.owner_id RETURNING lease_key",[key,ownerId,Math.max(10,Math.min(3600,ttlSeconds))]); return r.rowCount===1; }
  async renewLease(key,ownerId,ttlSeconds=300){const r=await this.pool.query('UPDATE discovery_leases SET expires_at=NOW()+make_interval(secs=>$3),updated_at=NOW() WHERE lease_key=$1 AND owner_id=$2 AND expires_at>NOW() RETURNING lease_key',[key,ownerId,Math.max(10,Math.min(3600,ttlSeconds))]);return r.rowCount===1;}
  async releaseLease(key,ownerId){const r=await this.pool.query('DELETE FROM discovery_leases WHERE lease_key=$1 AND owner_id=$2',[key,ownerId]);return r.rowCount===1;}
  async failAbandonedRuns(maxAgeSeconds=3600){const r=await this.pool.query("UPDATE discovery_source_runs SET status='failed',completed_at=NOW(),error_message='worker lease expired before completion' WHERE status='running' AND started_at<NOW()-make_interval(secs=>$1) RETURNING id",[Math.max(60,maxAgeSeconds)]);return r.rows.map(x=>x.id);}
  async recordCanary(sourceKey,{clean,scope={},runId=null}){if(!scope||typeof scope!=='object'||Array.isArray(scope)||!Object.keys(scope).length)throw new Error('Canary scope must describe the complete publisher slice');const scopeHash=hash(scope);const r=await this.pool.query("INSERT INTO discovery_source_rollouts(source_key,state,clean_canary_runs,configured_scope,canary_scope_hash,last_clean_run_id) VALUES($1,'canary',$2,$3,$4,CASE WHEN $2=1 THEN $5::uuid ELSE NULL END) ON CONFLICT(source_key) DO UPDATE SET state=CASE WHEN discovery_source_rollouts.state='promoted' THEN 'promoted' ELSE 'canary' END,clean_canary_runs=CASE WHEN $2=1 AND discovery_source_rollouts.canary_scope_hash=$4 AND ($5::uuid IS NULL OR discovery_source_rollouts.last_clean_run_id IS DISTINCT FROM $5::uuid) THEN discovery_source_rollouts.clean_canary_runs+1 WHEN $2=1 THEN 1 ELSE 0 END,configured_scope=$3,canary_scope_hash=$4,last_clean_run_id=CASE WHEN $2=1 THEN $5::uuid ELSE NULL END,updated_at=NOW() RETURNING *",[sourceKey,clean?1:0,scope,scopeHash,runId]);return r.rows[0];}
  async promoteSource(sourceKey){const r=await this.pool.query("UPDATE discovery_source_rollouts SET state='promoted',promoted_at=NOW(),updated_at=NOW() WHERE source_key=$1 AND clean_canary_runs>=2 AND configured_scope<>'{}'::jsonb RETURNING *",[sourceKey]);if(!r.rows[0])throw new Error('Source needs configured scope and two clean canary runs');return r.rows[0];}
  async promotedSources(){const r=await this.pool.query("SELECT source_key FROM discovery_source_rollouts WHERE state='promoted'");return r.rows.map(x=>x.source_key);}
  async createOrReuseJob(input={}){const key=input.idempotencyKey||null,id=collectionJobId(),sources=[...new Set((input.sourceIds||[]).map(String))].sort(),payload=input.payload||{},kind=input.kind||'property',trigger=input.trigger||'manual',scopeHash=hash({kind,trigger,sourceIds:sources,payload});const stages={collection:{status:'queued'},inventory:{status:'queued'},observations:{status:'queued'},hunts:{status:'queued'},cases:{status:'queued'}};const r=await this.pool.query("INSERT INTO discovery_jobs(id,idempotency_key,idempotency_scope_hash,kind,trigger,status,source_keys,payload,stages) VALUES($1,$2,$3,$4,$5,'queued',$6,$7::jsonb,$8::jsonb) ON CONFLICT(idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key WHERE discovery_jobs.idempotency_scope_hash=EXCLUDED.idempotency_scope_hash RETURNING *",[id,key,scopeHash,kind,trigger,sources,JSON.stringify(payload),JSON.stringify(stages)]);if(!r.rows[0])throw new Error('Idempotency key is already bound to a different collection scope');return this.jobRow(r.rows[0]);}
  jobRow(row){if(!row)return null;return {id:row.id,idempotencyKey:row.idempotency_key,kind:row.kind,trigger:row.trigger,sourceIds:row.source_keys,status:row.status,revision:row.revision,createdAt:row.created_at,startedAt:row.started_at,completedAt:row.completed_at,leaseOwner:row.lease_owner||null,leaseExpiresAt:row.lease_expires_at||null,attemptCount:row.attempt_count||0,stages:jsonValue(row.stages,{}),errors:jsonValue(row.errors,[]),result:jsonValue(row.result,null)};}
  async claimJob(id,ownerId,ttlSeconds=300){const r=await this.pool.query("UPDATE discovery_jobs SET status='running',lease_owner=$2,lease_expires_at=NOW()+make_interval(secs=>$3),started_at=coalesce(started_at,NOW()),attempt_count=attempt_count+1,revision=revision+1 WHERE id=$1 AND (status='queued' OR (status='running' AND lease_expires_at<NOW())) RETURNING *",[id,ownerId,Math.max(10,Math.min(3600,ttlSeconds))]);return this.jobRow(r.rows[0]);}
  async claimNextJob(ownerId,ttlSeconds=300){const r=await this.pool.query("WITH candidate AS (SELECT id FROM discovery_jobs WHERE status='queued' OR (status='running' AND lease_expires_at<NOW()) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE discovery_jobs j SET status='running',lease_owner=$1,lease_expires_at=NOW()+make_interval(secs=>$2),started_at=coalesce(j.started_at,NOW()),attempt_count=j.attempt_count+1,revision=j.revision+1 FROM candidate WHERE j.id=candidate.id RETURNING j.*",[ownerId,Math.max(10,Math.min(3600,ttlSeconds))]);return this.jobRow(r.rows[0]);}
  async renewJobClaim(id,ownerId,ttlSeconds=300){const r=await this.pool.query("UPDATE discovery_jobs SET lease_expires_at=NOW()+make_interval(secs=>$3),revision=revision+1 WHERE id=$1 AND lease_owner=$2 AND status='running' AND lease_expires_at>NOW() RETURNING id",[id,ownerId,Math.max(10,Math.min(3600,ttlSeconds))]);return r.rowCount===1;}
  async getJob(id){const r=await this.pool.query('SELECT * FROM discovery_jobs WHERE id=$1',[id]);return this.jobRow(r.rows[0]);}
  async listJobs(limit=50){const bounded=Math.max(1,Math.min(50,Number(limit)||50));const r=await this.pool.query('SELECT * FROM discovery_jobs ORDER BY created_at DESC LIMIT $1',[bounded]);const total=Number((await this.pool.query('SELECT count(*)::int AS count FROM discovery_jobs')).rows[0].count);return {items:r.rows.map(x=>this.jobRow(x)),total};}
  async updateJob(id,update={},options={}){const current=await this.getJob(id);if(!current)throw new Error('Collection job was not found');const stages={...(current.stages&&typeof current.stages==='object'?current.stages:{})},errors=Array.isArray(current.errors)?[...current.errors]:[];if(update.stage)stages[update.stage.name]={...(stages[update.stage.name]||{}),...update.stage.value,updatedAt:new Date().toISOString()};if(update.error)errors.push({stage:update.error.stage||'collection',message:String(update.error.message||update.error).slice(0,500),at:new Date().toISOString()});const result=update.result===undefined?null:JSON.stringify(update.result);const r=await this.pool.query('UPDATE discovery_jobs SET status=coalesce($2,status),stages=$3::jsonb,errors=$4::jsonb,result=coalesce($5::jsonb,result),started_at=CASE WHEN $6 AND started_at IS NULL THEN NOW() ELSE started_at END,completed_at=CASE WHEN $7 THEN NOW() ELSE completed_at END,revision=revision+1 WHERE id=$1 AND ($8::text IS NULL OR (lease_owner=$8 AND lease_expires_at>NOW())) RETURNING *',[id,update.status||null,JSON.stringify(stages),JSON.stringify(errors),result,Boolean(update.started),Boolean(update.completed),options.ownerId||null]);if(!r.rows[0]&&options.ownerId)throw new Error('Collection job lease was lost; refusing stale update');return this.jobRow(r.rows[0]);}
}
module.exports={DiscoveryStore,hash,createDiscoveryStore:(database)=>new DiscoveryStore(database.pool||database)};
