'use strict';

/**
 * Discovery and evidence catalog.  This is deliberately not a runtime-health
 * registry: an entry says where a source can be investigated, not that it is
 * currently reachable or has inventory.  Runtime health belongs to scheduler
 * telemetry and source-observed listings.
 */

const SCHEDULED_ADAPTER_KEYS = Object.freeze([
  'treasury', 'gsa', 'irs', 'usda', 'landbank', 'civilview', 'bid4assets',
  'sheriff', 'hud', 'fannie', 'freddie', 'va', 'marshals', 'servicelink'
]);

const ROLES = new Set(['opportunity', 'evidence', 'discovery']);
const ACCESS = new Set(['public', 'account', 'licensed', 'jurisdiction']);

function source(entry) {
  if (!ROLES.has(entry.role)) throw new TypeError(`Invalid source role: ${entry.role}`);
  if (!ACCESS.has(entry.access)) throw new TypeError(`Invalid source access: ${entry.access}`);
  if (entry.propertyLookup !== undefined && typeof entry.propertyLookup !== 'boolean') {
    throw new TypeError(`propertyLookup must be a boolean: ${entry.id}`);
  }
  if (entry.adapterKey !== null && !SCHEDULED_ADAPTER_KEYS.includes(entry.adapterKey)) {
    throw new TypeError(`Unknown scheduled adapter: ${entry.adapterKey}`);
  }
  return Object.freeze({
    ...entry,
    workflow: Object.freeze({ ...entry.workflow, steps: Object.freeze([...entry.workflow.steps]) }),
    requiredEvidence: Object.freeze([...entry.requiredEvidence])
  });
}

const recordEvidence = ['exact publisher record URL', 'source-observed timestamp', 'sale terms or offer terms'];
const parcelEvidence = ['APN or legal description', 'jurisdiction record URL', 'source-observed timestamp'];

const SOURCE_CATALOG = Object.freeze([
  source({ id: 'alachua-tax-deeds', label: 'Alachua County Tax-Deed Records', category: 'tax_sale', role: 'opportunity', coverage: 'Reviewed Alachua County case imports; no automated current county inventory.', discoveryUrl: 'https://alachuacounty.us/Depts/Clerk/TaxDeeds/Pages/TaxDeedSales.aspx', access: 'public', adapterKey: null, workflow: { primary: 'Import exact current county case records and approve the evidence before running the county pilot.', fallback: 'Use a reviewed public export or original case documents from the county-designated portals.', cadenceHours: 24, steps: ['Capture the exact case URL, publisher ID, explicit status, intact parcel IDs, observation time, and available original-document links.', 'Import structured JSON through source intake and review its original evidence.', 'Compare approved observations, run the county pilot, then confirm current availability and obtain a current purchase quote from the clerk.'] }, requiredEvidence: ['exact county portal case URL and publisher ID', 'explicit recorded case status', 'intact Alachua parcel identifiers', 'capture time and approved evidence review', 'separately identified published cost components and unresolved current quote'], notes: 'A passed auction date does not establish public-purchase availability. Program terms, a prior opening bid, and a current purchase quote remain separate. Imported evidence is not automatically published as live inventory.' }),
  source({ id: 'alachua-county-parcels', label: 'Alachua County Parcel and Planning Records', category: 'parcel_evidence', role: 'evidence', coverage: 'Bounded exact-identifier lookups of Alachua County public GIS parcel records.', discoveryUrl: 'https://maps.alachuacounty.us/server/rest/services/Hosted/ParcelsACGM/FeatureServer/0', access: 'public', adapterKey: null, propertyLookup: true, workflow: { primary: 'Query the fixed county parcel API using an intact Alachua parcel ID.', fallback: 'Inspect the county property-appraiser record and original planning references.', cadenceHours: 720, steps: ['Confirm Alachua County scope and preserve the original parcel ID.', 'Capture the exact query, assessment year, geometry, and match state.', 'Compare dated parcel facts with the offering and retain unresolved planning questions.'] }, requiredEvidence: ['Alachua parcel identifier', 'exact official query URL', 'assessment year and observation time'], notes: 'Assessor values are not market valuations. Jurisdiction and wetland-review codes require their documented meanings; planning fields do not establish development rights or occupancy.' }),
  source({ id: 'servicelink', label: 'Public Auction Network', category: 'foreclosure_auction', role: 'opportunity', coverage: 'Public auction listing feed across publisher-reported sale programs; collected coverage is bounded by the configured page budget.', discoveryUrl: 'https://www.servicelinkauction.com/', access: 'public', adapterKey: 'servicelink', workflow: { primary: 'Collect the public listings feed and preserve each exact property record and source status.', fallback: 'Use the public property record and import an authorized notice/export for review.', cadenceHours: 6, steps: ['Collect a bounded page of public listings.', 'Match the exact property record and retain its publisher identifiers.', 'Confirm current sale status, opening bid, payment terms, and location before acting.'] }, requiredEvidence: [...recordEvidence, 'publisher listing identifier', 'source-reported auction program and status'], notes: 'Public listing data only. No account, bidding, administrative, or private APIs are used. A search total is not a claim that all records were collected.' }),
  source({ id: 'hud-homestore', label: 'HUD HomeStore', category: 'government_reo', role: 'opportunity', coverage: 'Nationwide HUD-owned single-family inventory; availability varies.', discoveryUrl: 'https://www.hudhomestore.gov/', access: 'public', adapterKey: 'hud', workflow: { primary: 'Use the publisher search and exact property detail page.', fallback: 'Manual, permissioned export or broker-assisted lookup; do not bypass publisher controls.', cadenceHours: 24, steps: ['Search by target state or ZIP.', 'Capture the exact case-number detail URL.', 'Record bid period, offer rules, and observed time.'] }, requiredEvidence: [...recordEvidence, 'HUD case number'], notes: 'Publisher access and automation rules can change; catalog entry does not assert a live feed.' }),
  source({ id: 'fannie-homepath', label: 'Fannie Mae HomePath', category: 'government_reo', role: 'opportunity', coverage: 'Nationwide Fannie Mae REO marketed through HomePath.', discoveryUrl: 'https://www.homepath.com/', access: 'public', adapterKey: 'fannie', workflow: { primary: 'Use HomePath search and a stable property detail URL.', fallback: 'Use an authorized broker or approved data relationship where a public page is unavailable.', cadenceHours: 24, steps: ['Search the intended market.', 'Save the property detail URL and listing identifier.', 'Confirm First Look or offer-window terms.'] }, requiredEvidence: [...recordEvidence, 'HomePath property identifier'], notes: 'Search presentation is dynamic; public discovery is not a license for bulk collection.' }),
  source({ id: 'freddie-homesteps', label: 'Freddie Mac HomeSteps', category: 'government_reo', role: 'opportunity', coverage: 'Nationwide Freddie Mac REO marketed through HomeSteps.', discoveryUrl: 'https://www.homesteps.com/', access: 'public', adapterKey: 'freddie', workflow: { primary: 'Use HomeSteps search and exact property page.', fallback: 'Use the listing broker or authorized data relationship.', cadenceHours: 24, steps: ['Filter by target market.', 'Preserve exact property URL and identifier.', 'Confirm offer and buyer eligibility terms.'] }, requiredEvidence: [...recordEvidence, 'HomeSteps property identifier'], notes: 'Availability and data access are publisher-controlled.' }),
  source({ id: 'usda-resales', label: 'USDA RD/FSA Property Resales', category: 'government_reo', role: 'opportunity', coverage: 'Nationwide USDA rural housing, farm, and ranch resales; inventory varies by state.', discoveryUrl: 'https://www.resales.usda.gov/resales/public/searchSFH', access: 'public', adapterKey: 'usda', workflow: { primary: 'Search USDA resales by state and save the property detail page.', fallback: 'Use the relevant USDA state office contact published on the sale.', cadenceHours: 24, steps: ['Search SFH and FSA offerings separately.', 'Capture listing detail and offering terms.', 'Check sale status immediately before action.'] }, requiredEvidence: [...recordEvidence, 'USDA listing identifier'], notes: 'USAGov identifies USDA as a federal source for homes, farms, and ranches.' }),
  source({ id: 'va-vrm', label: 'VA REO / VRM Properties', category: 'government_reo', role: 'opportunity', coverage: 'Nationwide VA-owned property marketed by its contractor; inventory varies.', discoveryUrl: 'https://www.vrmproperties.com/', access: 'public', adapterKey: 'va', workflow: { primary: 'Use VRM public property search and exact listing.', fallback: 'Contact the named listing broker or property manager.', cadenceHours: 24, steps: ['Search the target geography.', 'Store exact VRM property URL.', 'Verify offer instructions and status with the publisher.'] }, requiredEvidence: [...recordEvidence, 'VA/VRM property identifier'], notes: 'Registration or broker involvement may be required to submit an offer.' }),
  source({ id: 'irs-auctions', label: 'IRS Auctions', category: 'government_seizure', role: 'opportunity', coverage: 'Nationwide IRS seized-real-property auction notices; low and irregular volume.', discoveryUrl: 'https://www.irsauctions.gov/', access: 'public', adapterKey: 'irs', workflow: { primary: 'Browse auction notices and use the exact auction/ad page.', fallback: 'Contact the named IRS sale contact in the official notice.', cadenceHours: 12, steps: ['Filter for real property.', 'Capture legal description, date, deposit, and terms.', 'Recheck before bid because notices can change.'] }, requiredEvidence: [...recordEvidence, 'official IRS notice or auction ID'], notes: 'Do not infer lien priority or condition from the listing alone.' }),
  source({ id: 'treasury-forfeiture', label: 'Treasury Forfeiture Real Property', category: 'government_seizure', role: 'opportunity', coverage: 'Nationwide Treasury forfeited real property, commonly marketed through a contractor.', discoveryUrl: 'https://www.treasury.gov/auctions/treasury/rp/realprop.shtml', access: 'public', adapterKey: 'treasury', workflow: { primary: 'Use the Treasury real-property page and linked offering record.', fallback: 'Use the named disposal contractor and preserve its offering URL.', cadenceHours: 12, steps: ['Review active real-property offerings.', 'Capture linked property record and terms.', 'Confirm closing, title, and occupancy terms.'] }, requiredEvidence: [...recordEvidence, 'forfeiture sale notice'], notes: 'An auction collection page is discovery, not evidence for an individual property.' }),
  source({ id: 'gsa-real-estate-sales', label: 'GSA Real Estate Sales', category: 'government_surplus', role: 'opportunity', coverage: 'Nationwide federal surplus real property; sparse, episodic inventory.', discoveryUrl: 'https://realestatesales.gov/', access: 'public', adapterKey: 'gsa', workflow: { primary: 'Use GSA search and the exact asset-details page.', fallback: 'Contact the GSA sales contact named in the offering.', cadenceHours: 24, steps: ['Filter for real property.', 'Capture asset-details URL and solicitation documents.', 'Confirm bid method and deadlines.'] }, requiredEvidence: [...recordEvidence, 'GSA property or solicitation ID'], notes: 'GSA personal-property auction APIs are not substitutes for real-estate records.' }),
  source({ id: 'us-marshals', label: 'U.S. Marshals Asset Forfeiture', category: 'government_seizure', role: 'opportunity', coverage: 'Nationwide DOJ forfeited real property; generally brokered and irregular.', discoveryUrl: 'https://www.usmarshals.gov/what-we-do/asset-forfeiture', access: 'public', adapterKey: 'marshals', workflow: { primary: 'Start at USMS, then use the named broker or RealLook property record.', fallback: 'Contact the assigned contractor or broker.', cadenceHours: 24, steps: ['Locate real-property disposition information.', 'Capture the broker record and USMS provenance.', 'Verify status with the named representative.'] }, requiredEvidence: [...recordEvidence, 'USMS or designated-contractor provenance'], notes: 'USMS states that most real property is sold through licensed brokers and its contractor.' }),
  source({ id: 'fdic-asset-sales', label: 'FDIC Asset Sales', category: 'government_reo', role: 'opportunity', coverage: 'Failed-bank real estate and property sales; current inventory may be empty.', discoveryUrl: 'https://www.fdic.gov/asset-sales/real-estate-and-property-sales', access: 'public', adapterKey: null, workflow: { primary: 'Use FDIC current real-estate/property sales and bargain-property pages.', fallback: 'Use FDIC Asset Sales contact and event calendar.', cadenceHours: 24, steps: ['Check current offerings.', 'Keep current listings separate from historical sales data.', 'Preserve FDIC page and any offering documents.'] }, requiredEvidence: [...recordEvidence, 'current FDIC offering document'], notes: 'The existing FDIC scraper is historical/fixture-oriented and is intentionally not scheduled as live opportunity ingestion.' }),
  source({ id: 'ncua-amac', label: 'NCUA AMAC Loan Sales & Available Real Estate', category: 'government_reo', role: 'opportunity', coverage: 'Failed or conserved credit-union asset sales; infrequent and often pooled.', discoveryUrl: 'https://ncua.gov/support-services/conservatorships-liquidations/loan-sales-available-real-estate', access: 'account', adapterKey: null, workflow: { primary: 'Monitor official NCUA sale page and interested-party sign-up.', fallback: 'Contact NCUA AMAC for current sale process.', cadenceHours: 168, steps: ['Check the scheduled asset-sales table.', 'Register or execute confidentiality documents when required.', 'Treat loan pools and individual real estate as distinct inventory.'] }, requiredEvidence: ['official NCUA sale page', 'sale-specific terms', 'qualified-bidder documentation when required'], notes: 'NCUA says a confidentiality agreement and deposit can be required; no current sale should be represented as inventory.' }),
  source({ id: 'blm-public-land-sales', label: 'BLM Federal Public Land Sales', category: 'government_land', role: 'opportunity', coverage: 'Selected undeveloped public land, primarily western states; rare and local-office administered.', discoveryUrl: 'https://www.blm.gov/programs/lands-and-realty/sales-and-exchanges/federal-public-land-sales-faqs', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Follow the target BLM state or field office sale notice.', fallback: 'Use BLM lands potentially available for disposal as a lead only.', cadenceHours: 168, steps: ['Identify the managing field office.', 'Find the official sale notice.', 'Review legal description, bid method, and eligibility.'] }, requiredEvidence: ['official BLM sale notice', 'legal description', 'bid terms and deposit requirement'], notes: 'BLM says it only occasionally sells selected parcels; it is not a nationwide inventory feed.' }),
  source({ id: 'cws-marketing', label: 'CWS Marketing Group (Treasury contractor)', category: 'government_seizure', role: 'opportunity', coverage: 'Treasury forfeiture contractor listings and broker sales; overlap with Treasury is expected.', discoveryUrl: 'https://cwsmarketing.com/auctions/real-estate/', access: 'public', adapterKey: null, workflow: { primary: 'Use contractor offering page only when linked to a specific property.', fallback: 'Reconcile every record to Treasury notice or named agency.', cadenceHours: 12, steps: ['Find real-estate offering.', 'Preserve the exact contractor detail page.', 'Link it to federal disposition provenance.'] }, requiredEvidence: [...recordEvidence, 'agency or contractor sale authority'], notes: 'Deduplicate against Treasury by source record and address; contractor page is not independent ownership evidence.' }),
  source({ id: 'real-look', label: 'RealLook (USMS real-property contractor)', category: 'government_seizure', role: 'opportunity', coverage: 'USMS brokered forfeited real property; inventory is national but intermittent.', discoveryUrl: 'https://www.reallook.com/', access: 'public', adapterKey: null, workflow: { primary: 'Use the exact RealLook property record and retain its USMS linkage.', fallback: 'Use the assigned broker contact.', cadenceHours: 24, steps: ['Search properties.', 'Capture exact listing URL.', 'Verify agency provenance and status.'] }, requiredEvidence: [...recordEvidence, 'USMS/contractor relationship evidence'], notes: 'RealLook is a contractor channel, not a substitute for title or sale terms.' }),
  source({ id: 'civilview', label: 'CivilView Sheriff/Tax Sale Platform', category: 'foreclosure_auction', role: 'opportunity', coverage: 'Participating jurisdictions, especially county sheriff and tax-sale programs; not nationwide.', discoveryUrl: 'https://salesweb.civilview.com/Sales/SalesSearch', access: 'jurisdiction', adapterKey: 'civilview', workflow: { primary: 'Enroll one county at a time and use the county-specific sale search plus exact sale details.', fallback: 'Use the county sheriff, treasurer, or clerk publisher page.', cadenceHours: 12, steps: ['Select an onboarded county.', 'Capture exact SaleDetails record.', 'Verify notice and sale terms with the issuing office.'] }, requiredEvidence: [...recordEvidence, 'issuing county notice'], notes: 'A generic county-search page is discovery, never an exact property record.' }),
  source({ id: 'bid4assets', label: 'Bid4Assets', category: 'foreclosure_auction', role: 'opportunity', coverage: 'Participating government and private auctions across multiple jurisdictions; scope varies by auction.', discoveryUrl: 'https://www.bid4assets.com/', access: 'account', adapterKey: 'bid4assets', workflow: { primary: 'Use the exact auction detail page and issuer documents.', fallback: 'Verify directly with the government agency or trustee named in auction terms.', cadenceHours: 12, steps: ['Filter to real estate.', 'Capture exact auction ID URL.', 'Read deposits, title, and redemption terms.'] }, requiredEvidence: [...recordEvidence, 'issuing-agency or trustee terms'], notes: 'Account or bidder registration may be required; marketplace inventory must retain issuer provenance.' }),
  source({ id: 'landbanksearch', label: 'Land Bank Search', category: 'land_bank', role: 'opportunity', coverage: 'Participating land banks; a discovery layer, not every U.S. land bank.', discoveryUrl: 'https://www.landbanksearch.com/', access: 'public', adapterKey: 'landbank', workflow: { primary: 'Use exact property record and reconcile to the owning land bank.', fallback: 'Use each local land bank’s official inventory.', cadenceHours: 24, steps: ['Search target market.', 'Capture property record and owning entity.', 'Verify availability and program restrictions with owner.'] }, requiredEvidence: [...recordEvidence, 'owning land-bank record'], notes: 'Terms can include redevelopment, owner-occupancy, or application obligations.' }),
  source({ id: 'cuyahoga-land-bank', label: 'Cuyahoga County Land Bank', category: 'land_bank', role: 'opportunity', coverage: 'Cuyahoga County, Ohio available-property inventory.', discoveryUrl: 'https://cuyahogalandbank.org/all-available-properties/', access: 'public', adapterKey: null, workflow: { primary: 'Use the official available-properties list and individual program materials.', fallback: 'Use the land bank property inquiry process.', cadenceHours: 24, steps: ['Search by address or parcel.', 'Capture official availability and program status.', 'Confirm acquisition requirements.'] }, requiredEvidence: [...parcelEvidence, 'land-bank availability or application terms'], notes: 'This concrete jurisdiction example validates the local-land-bank workflow; it is not a nationwide proxy.' }),
  source({ id: 'ohio-sheriff-sale', label: 'Ohio Sheriff Sale Auction', category: 'foreclosure_auction', role: 'opportunity', coverage: 'Participating Ohio sheriff-sale jurisdictions.', discoveryUrl: 'https://sheriffsaleauction.ohio.gov/', access: 'jurisdiction', adapterKey: 'sheriff', workflow: { primary: 'Use participating county auction record and sheriff notice.', fallback: 'Use that county sheriff civil-sales page.', cadenceHours: 12, steps: ['Choose a participating county.', 'Capture exact sale/case record.', 'Confirm court status and bidder rules.'] }, requiredEvidence: [...recordEvidence, 'county sheriff or court notice'], notes: 'Only participating counties are covered; county adoption and rules vary.' }),
  source({ id: 'county-trustee-sale', label: 'County Trustee Sale Publisher', category: 'foreclosure_auction', role: 'opportunity', coverage: 'Jurisdiction-specific nonjudicial foreclosure sales; state law and publisher vary.', discoveryUrl: 'https://www.usa.gov/state-local-governments', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Enroll the statutory trustee or county notice publisher for a selected jurisdiction.', fallback: 'Use recorder notices and the named trustee contact.', cadenceHours: 12, steps: ['Identify statutory foreclosure process.', 'Locate official notice publisher.', 'Capture exact notice, sale date, and trustee terms.'] }, requiredEvidence: ['trustee notice or sale record', 'legal description or APN', 'sale date and bidder terms'], notes: 'No universal trustee-sale endpoint exists; this is a per-jurisdiction enrollment template.' }),
  source({ id: 'harris-county-tax-sale', label: 'Harris County, TX Tax Sale', category: 'tax_sale', role: 'opportunity', coverage: 'Harris County, Texas delinquent tax, execution, and resale auctions.', discoveryUrl: 'https://www.hctax.net/Property/TaxSales', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Use the county tax-sale notice and registered-bidder process.', fallback: 'Use the Daily Court Review named by the county and verify with the tax office.', cadenceHours: 24, steps: ['Review monthly sale notices.', 'Complete bidder registration if required.', 'Capture exact property and sale terms.'] }, requiredEvidence: ['Harris County sale notice', 'parcel or legal description', 'bidder-registration and sale terms'], notes: 'The county states sales are monthly and bidder registration is required.' }),
  source({ id: 'maricopa-tax-deed', label: 'Maricopa County, AZ Tax-Deeded Land Sales', category: 'tax_sale', role: 'opportunity', coverage: 'Maricopa County, Arizona state-held tax-deeded parcel auctions as scheduled.', discoveryUrl: 'https://www.maricopa.gov/780/Tax-Deeded-Land-Sales', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Use county tax-deeded-land sale notice.', fallback: 'Contact the County Treasurer.', cadenceHours: 168, steps: ['Monitor as-needed sale announcements.', 'Capture auction notice and parcel data.', 'Verify deed, redemption, and bidding rules.'] }, requiredEvidence: ['County Treasurer sale notice', 'parcel/legal description', 'auction terms'], notes: 'This is tax-deeded land, not a generic tax-lien feed.' }),
  source({ id: 'county-tax-sale-template', label: 'County Tax Lien/Deed Sale Template', category: 'tax_sale', role: 'opportunity', coverage: 'Any enrolled county tax collector, treasurer, or delinquent-tax office.', discoveryUrl: 'https://www.usa.gov/local-governments', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Enroll official county tax-sale endpoint after manual verification.', fallback: 'Use county treasurer contact and local public notice.', cadenceHours: 24, steps: ['Identify lien versus deed regime.', 'Validate issuer domain and sale calendar.', 'Capture official notice and redemption rules.'] }, requiredEvidence: ['official county notice', 'parcel/legal description', 'sale type', 'redemption and bidder terms'], notes: 'Each county must be enrolled separately; tax lien does not mean immediate ownership.' }),
  source({ id: 'county-surplus-property', label: 'County/Municipal Surplus Real Property', category: 'local_surplus', role: 'opportunity', coverage: 'Jurisdiction-specific excess land, buildings, RFPs, and sealed-bid sales.', discoveryUrl: 'https://www.usa.gov/local-governments', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Enroll a local surplus-property or procurement publisher.', fallback: 'Monitor city council agendas and procurement office notices.', cadenceHours: 168, steps: ['Verify the disposing authority.', 'Capture RFP, auction, or bid packet.', 'Record parcel, restrictions, and deadline.'] }, requiredEvidence: ['official disposal notice or bid packet', 'parcel/legal description', 'authority and transfer terms'], notes: 'This channel is fragmented and usually has no standardized national feed.' }),
  source({ id: 'state-land-auctions', label: 'State Trust/Public Land Auction Office', category: 'government_land', role: 'opportunity', coverage: 'State-specific trust or public land sale programs.', discoveryUrl: 'https://www.usa.gov/state-government', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Enroll a selected state land office and sale calendar.', fallback: 'Use state procurement or land-management notices.', cadenceHours: 168, steps: ['Select a state.', 'Validate the administering agency and auction notice.', 'Capture legal description and eligibility.'] }, requiredEvidence: ['state agency sale notice', 'legal description', 'auction or bid terms'], notes: 'State authority, inventory, and buyer restrictions differ substantially.' }),
  source({ id: 'state-surplus-property', label: 'State Surplus Real Property Office', category: 'government_surplus', role: 'opportunity', coverage: 'State agency excess real estate programs; state-by-state.', discoveryUrl: 'https://www.usa.gov/state-government', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Enroll a state surplus-property or procurement office.', fallback: 'Use state public-notice register and agency contacts.', cadenceHours: 168, steps: ['Identify state real-property disposal authority.', 'Find exact solicitation.', 'Record sale method and transfer conditions.'] }, requiredEvidence: ['state disposal notice', 'property legal description', 'bid/offer terms'], notes: 'Personal-property surplus portals should be excluded unless the offering is expressly real property.' }),
  source({ id: 'federal-register', label: 'Federal Register Notices', category: 'public_notice', role: 'discovery', coverage: 'Federal notices, proposed actions, and occasional real-property disposition signals.', discoveryUrl: 'https://www.federalregister.gov/', access: 'public', adapterKey: null, workflow: { primary: 'Search agency and real-property terms, then follow the underlying agency notice.', fallback: 'Use agency press release or official property-sale page.', cadenceHours: 24, steps: ['Search target agency and location.', 'Treat results as leads.', 'Resolve to exact agency sale record before creating listing.'] }, requiredEvidence: ['underlying agency offering record', 'source-observed timestamp'], notes: 'Federal Register notices are discovery evidence, not property inventory by themselves.' }),
  source({ id: 'jurisdiction-public-notices', label: 'Jurisdiction Public Notices', category: 'public_notice', role: 'discovery', coverage: 'County/state newspapers, clerk postings, and statutory notice systems.', discoveryUrl: 'https://www.usa.gov/local-governments', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Enroll a specific statutory publisher after identifying its issuing authority.', fallback: 'Use clerk, sheriff, trustee, or treasurer original notice.', cadenceHours: 12, steps: ['Identify the legal notice source.', 'Confirm publication and issuing jurisdiction.', 'Resolve each notice to its court or sale record.'] }, requiredEvidence: ['notice image/text', 'issuing authority', 'case or parcel identifier'], notes: 'Publisher names, formats, and access vary; OCR-derived fields require source verification.' }),
  source({ id: 'pacer-bankruptcy', label: 'PACER Bankruptcy and Federal Court Records', category: 'court_record', role: 'discovery', coverage: 'Nationwide federal bankruptcy, district, and appellate court indexes and records.', discoveryUrl: 'https://www.uscourts.gov/court-records/find-a-case-pacer', access: 'account', adapterKey: null, workflow: { primary: 'Use PACER Case Locator to find a case, then the court docket for supporting records.', fallback: 'Use a public clerk terminal where applicable.', cadenceHours: 24, steps: ['Search party, case, or court.', 'Record docket number and filed document reference.', 'Do not make a property listing without a sale/asset record.'] }, requiredEvidence: ['case number', 'docket entry or filed sale document', 'property linkage'], notes: 'PACER has account and fee conditions; bankruptcy filing is not itself a sale.' }),
  source({ id: 'state-court-dockets', label: 'State/Local Court Docket Publisher', category: 'court_record', role: 'evidence', coverage: 'Jurisdiction-specific foreclosure, probate, receivership, and tax litigation records.', discoveryUrl: 'https://www.ncsc.org/information-and-resources/browse-by-state/state-court-websites', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Enroll the official court docket provider for a selected jurisdiction.', fallback: 'Use clerk records or in-person public terminal.', cadenceHours: 24, steps: ['Select court and case type.', 'Verify party/case against sale notice.', 'Record docket evidence without assuming title outcome.'] }, requiredEvidence: ['court and case number', 'docket entry', 'jurisdiction source URL'], notes: 'Access and redaction policies vary by court.' }),
  source({ id: 'florida-statewide-parcels', label: 'Florida Statewide Cadastral', category: 'parcel_evidence', role: 'evidence', coverage: 'Florida Department of Revenue statewide cadastral and assessment-layer features; a queried feature still requires parcel-identity confirmation.', discoveryUrl: 'https://services9.arcgis.com/Gh9awoU677aKree0/arcgis/rest/services/Florida_Statewide_Cadastral/FeatureServer/0', access: 'public', adapterKey: null, propertyLookup: true, workflow: { primary: 'Query the fixed official FeatureServer with an exact Florida DOR county/parcel scope or source-observed coordinates, then validate the returned parcel identity.', fallback: 'Use the county property appraiser or assessor for a parcel-specific record.', cadenceHours: 720, steps: ['Require an APN plus Florida DOR county code, or source-observed coordinates.', 'Capture the exact official query URL and returned parcel identifier.', 'Retain assessment year and cadastral facts without treating them as valuation or survey conclusions.'] }, requiredEvidence: ['Florida DOR parcel identifier', 'Florida DOR county code or source-observed coordinates', 'official FeatureServer query URL', 'assessment year and source-observed timestamp'], notes: 'A point intersection can be a candidate rather than the subject parcel. Cadastral geometry is not a boundary survey, and assessed values are not market values.' }),
  source({ id: 'census-acs', label: 'Census ACS Public Area Context', category: 'area_context', role: 'evidence', coverage: 'Nationwide Census address geography and ACS five-year tract/county context; estimates describe areas, not individual properties.', discoveryUrl: 'https://www.census.gov/data/developers/data-sets/acs-5year.html', access: 'account', adapterKey: null, propertyLookup: true, workflow: { primary: 'Use a configured Census API key to match the exact source address to Census geography, then retrieve the documented ACS five-year geography response.', fallback: 'Use county-level ACS context when a tract match is unavailable, preserving the lower geographic precision.', cadenceHours: 720, steps: ['Confirm the source address and state before geocoding.', 'Capture the Census geography match, GEOID, dataset year, period, and query URL.', 'Present vacancy, income, and home-value fields only as area estimates with margins of error.'] }, requiredEvidence: ['configured Census API key entitlement', 'Census geography match and GEOID', 'ACS dataset year and period', 'official Census query URL and source-observed timestamp'], notes: 'The operator needs a Census API key. ACS vacancy and median home value do not establish this property’s occupancy or value.' }),
  source({ id: 'hud-usps-vacancy', label: 'HUD/USPS Vacancy Data', category: 'vacancy_evidence', role: 'evidence', coverage: 'HUD-published USPS aggregate vacancy and no-stat counts at Census-tract context; no property-address vacancy feed.', discoveryUrl: 'https://www.huduser.gov/portal/datasets/usps.html', access: 'licensed', adapterKey: null, workflow: { primary: 'Use only under HUD/USPS registered-user eligibility and the stated-purpose sublicense for the permitted government or nonprofit organization.', fallback: 'Use Census ACS area-vacancy context when no HUD/USPS entitlement exists.', cadenceHours: 2160, steps: ['Confirm eligible organization registration and permitted stated purpose.', 'Capture the Census tract, release quarter, and source dataset reference.', 'Present results as aggregate tract context, never as proof that a property is vacant.'] }, requiredEvidence: ['HUD/USPS registered-user eligibility and sublicense', 'Census tract and release quarter', 'dataset source reference and observed timestamp'], notes: 'HUD says access is restricted to registered government and nonprofit users for the stated purpose. USPS data are aggregate counts and do not identify whether a particular property is vacant.' }),
  source({ id: 'county-assessor', label: 'County Assessor/Appraiser', category: 'parcel_evidence', role: 'evidence', coverage: 'Parcel valuation and characteristics for an enrolled county.', discoveryUrl: 'https://www.usa.gov/local-governments', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Use official assessor search with APN/address.', fallback: 'Contact assessor office.', cadenceHours: 168, steps: ['Match parcel using APN and address.', 'Capture assessed facts and tax year.', 'Keep assessed value distinct from market value.'] }, requiredEvidence: [...parcelEvidence, 'assessment year'], notes: 'Assessor values are evidence, not an appraisal or bid recommendation.' }),
  source({ id: 'county-recorder', label: 'County Recorder/Clerk Land Records', category: 'title_evidence', role: 'evidence', coverage: 'Recorded deeds, liens, notices, and legal descriptions for an enrolled county.', discoveryUrl: 'https://www.usa.gov/local-governments', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Use official recorder search by grantor/grantee, instrument, or parcel.', fallback: 'Use recorder counter or certified records process.', cadenceHours: 168, steps: ['Find source instrument.', 'Capture recording number and date.', 'Escalate title conclusions to qualified title professional.'] }, requiredEvidence: ['recording/instrument number', 'recording date', 'official recorder URL'], notes: 'Recorded documents alone do not establish insurable title or lien priority.' }),
  source({ id: 'county-gis', label: 'County Parcel GIS', category: 'parcel_evidence', role: 'evidence', coverage: 'Parcel geometry and location context for an enrolled county.', discoveryUrl: 'https://www.usa.gov/local-governments', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Use official county GIS map/service.', fallback: 'Use assessor parcel map or GIS office contact.', cadenceHours: 168, steps: ['Match APN/address.', 'Capture source geometry and attribution.', 'Do not synthesize a boundary if the source has no parcel match.'] }, requiredEvidence: [...parcelEvidence, 'GIS layer/source attribution'], notes: 'Boundary accuracy and update cycles are jurisdiction-specific.' }),
  source({ id: 'local-zoning', label: 'Local Zoning and Planning', category: 'land_use_evidence', role: 'evidence', coverage: 'Municipal/county zoning maps, ordinances, and planning cases.', discoveryUrl: 'https://www.usa.gov/local-governments', access: 'jurisdiction', adapterKey: null, workflow: { primary: 'Use official zoning map and ordinance for a selected municipality.', fallback: 'Request zoning verification from planning department.', cadenceHours: 168, steps: ['Match parcel to jurisdiction.', 'Capture zoning district and ordinance reference.', 'Check overlays and pending cases.'] }, requiredEvidence: ['zoning map or ordinance URL', 'parcel/location match', 'effective date'], notes: 'Zoning interpretation and permitted use require local confirmation.' }),
  source({ id: 'fema-flood-map', label: 'FEMA Flood Map Service Center', category: 'hazard_evidence', role: 'evidence', coverage: 'Nationwide FEMA flood-map panels where mapped.', discoveryUrl: 'https://msc.fema.gov/portal/home', access: 'public', adapterKey: null, workflow: { primary: 'Search official FEMA map by address or coordinates.', fallback: 'Use local floodplain administrator for determination.', cadenceHours: 720, steps: ['Locate current panel.', 'Capture map panel/effective date.', 'Treat result as screening evidence.'] }, requiredEvidence: ['FEMA panel or official map URL', 'effective date', 'location match'], notes: 'FEMA mapping is not a complete flood-risk assessment.' }),
  source({ id: 'epa-envirofacts', label: 'EPA Environmental Screening', category: 'hazard_evidence', role: 'evidence', coverage: 'Nationwide EPA program data and environmental facility screening.', discoveryUrl: 'https://www.epa.gov/enviro', access: 'public', adapterKey: null, workflow: { primary: 'Use EPA program data for preliminary site screening.', fallback: 'Obtain professional environmental due diligence.', cadenceHours: 720, steps: ['Search address/nearby facilities.', 'Capture program record and source date.', 'Do not present screening hit as liability finding.'] }, requiredEvidence: ['EPA record URL or identifier', 'location relationship', 'source date'], notes: 'Environmental due diligence may require a Phase I ESA and professional review.' }),
  source({ id: 'usfws-wetlands', label: 'U.S. Fish & Wildlife Wetlands Mapper', category: 'hazard_evidence', role: 'evidence', coverage: 'Nationwide National Wetlands Inventory mapping coverage.', discoveryUrl: 'https://www.fws.gov/program/national-wetlands-inventory/wetlands-mapper', access: 'public', adapterKey: null, workflow: { primary: 'Screen parcel against official mapper.', fallback: 'Use qualified delineation and agency consultation.', cadenceHours: 720, steps: ['Match parcel/location.', 'Capture map layer attribution/date.', 'Flag uncertainty for field review.'] }, requiredEvidence: ['official mapper/source attribution', 'location match', 'map observation date'], notes: 'NWI data is screening information, not a jurisdictional wetland determination.' }),
  source({ id: 'auction-dot-com', label: 'Auction.com', category: 'marketplace', role: 'opportunity', coverage: 'Marketplace inventory across participating markets and sellers.', discoveryUrl: 'https://www.auction.com/', access: 'account', adapterKey: null, workflow: { primary: 'Use exact auction/property record and seller documents.', fallback: 'Verify with named trustee, lender, broker, or government issuer.', cadenceHours: 12, steps: ['Search target market.', 'Capture exact listing and auction ID.', 'Verify source authority and bidding terms.'] }, requiredEvidence: [...recordEvidence, 'named seller/issuer provenance'], notes: 'Commercial marketplace listings require issuer-level verification.' }),
  source({ id: 'hubzu', label: 'Hubzu', category: 'marketplace', role: 'opportunity', coverage: 'Marketplace foreclosure, REO, and auction inventory; seller coverage varies.', discoveryUrl: 'https://www.hubzu.com/', access: 'account', adapterKey: null, workflow: { primary: 'Use exact property record and auction documents.', fallback: 'Verify with the listing broker, trustee, or seller.', cadenceHours: 12, steps: ['Search target market.', 'Capture listing ID and terms.', 'Confirm current bid status before action.'] }, requiredEvidence: [...recordEvidence, 'seller or trustee evidence'], notes: 'Registration and auction-specific conditions can apply.' }),
  source({ id: 'xome', label: 'Xome Auctions', category: 'marketplace', role: 'opportunity', coverage: 'Marketplace auction and REO inventory; seller coverage varies.', discoveryUrl: 'https://www.xome.com/auctions/', access: 'account', adapterKey: null, workflow: { primary: 'Use exact property/auction record.', fallback: 'Verify through named seller, broker, or public notice.', cadenceHours: 12, steps: ['Search target market.', 'Capture record and auction ID.', 'Verify property terms and issuer.'] }, requiredEvidence: [...recordEvidence, 'issuer or listing-broker evidence'], notes: 'Marketplace listing alone is not title, condition, or legal-sale evidence.' }),
  source({ id: 'realauction', label: 'RealAuction Platform', category: 'tax_sale', role: 'opportunity', coverage: 'Participating county tax, foreclosure, and other online auctions.', discoveryUrl: 'https://www.realauction.com/', access: 'account', adapterKey: null, workflow: { primary: 'Enroll a specific county and use exact auction record.', fallback: 'Use county tax collector/sheriff original notice.', cadenceHours: 12, steps: ['Select participating jurisdiction.', 'Capture exact auction/property ID.', 'Verify sale type, redemption, and bidder rules.'] }, requiredEvidence: [...recordEvidence, 'issuing county authority'], notes: 'The platform is not the issuer; county-specific terms govern.' }),
  source({ id: 'govdeals-real-property', label: 'GovDeals Real Property', category: 'government_surplus', role: 'opportunity', coverage: 'Participating government/school/utility surplus offerings, including occasional real estate.', discoveryUrl: 'https://www.govdeals.com/', access: 'account', adapterKey: null, workflow: { primary: 'Filter to actual real estate and use exact listing.', fallback: 'Verify directly with the disposing public agency.', cadenceHours: 24, steps: ['Confirm offering is real property, not equipment.', 'Capture listing and agency contact.', 'Obtain agency terms and authority.'] }, requiredEvidence: [...recordEvidence, 'disposing-agency evidence'], notes: 'Exclude personal property from property inventory.' }),
  source({ id: 'mls-licensed-feed', label: 'MLS / Broker-Authorized Feed', category: 'marketplace', role: 'opportunity', coverage: 'Market-specific licensed MLS or broker data, potentially including REO and short sales.', discoveryUrl: 'https://www.nar.realtor/', access: 'licensed', adapterKey: null, workflow: { primary: 'Integrate only under an MLS/IDX or broker authorization.', fallback: 'Use public listing-broker property page.', cadenceHours: 6, steps: ['Obtain data license.', 'Honor display, attribution, and refresh rules.', 'Retain original broker/source URL.'] }, requiredEvidence: ['licensed feed entitlement', 'listing-broker attribution', 'listing ID and observed timestamp'], notes: 'There is no single national MLS feed; this requires market-level licensing.' })
]);

function getSource(id) {
  const normalized = String(id || '').trim().toLowerCase();
  return SOURCE_CATALOG.find((entry) => entry.id === normalized) || null;
}

function summarizeCatalog() {
  const byRole = {};
  const byCategory = {};
  const scheduledAdapterKeys = [];
  for (const entry of SOURCE_CATALOG) {
    byRole[entry.role] = (byRole[entry.role] || 0) + 1;
    byCategory[entry.category] = (byCategory[entry.category] || 0) + 1;
    if (entry.adapterKey) scheduledAdapterKeys.push(entry.adapterKey);
  }
  return Object.freeze({ total: SOURCE_CATALOG.length, byRole: Object.freeze(byRole), byCategory: Object.freeze(byCategory), scheduledAdapterKeys: Object.freeze(scheduledAdapterKeys.sort()) });
}

function isPrivateIpv4(hostname) {
  const parts = hostname.split('.').map(Number);
  if (parts.length !== 4 || parts.some((part) => !Number.isInteger(part) || part < 0 || part > 255)) return false;
  return parts[0] === 10 || parts[0] === 127 || parts[0] === 0 || (parts[0] === 169 && parts[1] === 254) || (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31) || (parts[0] === 192 && parts[1] === 168);
}

/** Pure validation only. Never resolves, fetches, or enrolls a submitted URL. */
function validateJurisdictionDiscoveryUrl(value) {
  let url;
  try { url = new URL(String(value || '').trim()); } catch (_) { return { isValid: false, error: 'invalid_url' }; }
  const hostname = url.hostname.toLowerCase().replace(/\.$/, '');
  if (url.protocol !== 'https:') return { isValid: false, error: 'https_required' };
  if (!hostname || hostname === 'localhost' || hostname.endsWith('.localhost') || isPrivateIpv4(hostname) || hostname === '::1') return { isValid: false, error: 'private_or_local_host' };
  if (url.username || url.password || url.port || url.hash) return { isValid: false, error: 'unsafe_url_component' };
  return { isValid: true, error: null, url: url.toString() };
}

module.exports = { SOURCE_CATALOG, SCHEDULED_ADAPTER_KEYS, getSource, summarizeCatalog, validateJurisdictionDiscoveryUrl };
