'use strict';
/*
 * gen-context.js — generate CONTEXT.md (the project domain model) from the repo
 * so the agent always has a fresh, single-source-of-truth view of:
 *   - the SOURCES taxonomy + LISTINGS (from data.js, loaded via VM like server/db)
 *   - the server API routes
 *   - the npm scripts
 *   - the invariants + run/test commands documented elsewhere
 *
 * The file embeds a CONTEXT-DIGEST. `--check` (and test/context.test.js) recompute
 * the digest and FAIL if CONTEXT.md is stale vs. its sources — so a change to
 * data.js / server routes / package.json that isn't followed by regeneration is
 * caught mechanically instead of rotting silently.
 *
 * Usage:
 *   node scripts/gen-context.js            # write CONTEXT.md
 *   node scripts/gen-context.js --check    # exit 1 if stale/missing
 *   node scripts/gen-context.js --json     # print facts as JSON (for tests)
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const CONTEXT_PATH = path.join(ROOT, 'CONTEXT.md');

function loadData() {
  const p = path.join(ROOT, 'data.js');
  const sandbox = { window: {}, Math };
  vm.createContext(sandbox);
  vm.runInContext(fs.readFileSync(p, 'utf8'), sandbox);
  return {
    sources: sandbox.window.SOURCES || {},
    listings: sandbox.window.LISTINGS || []
  };
}

function loadScripts() {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  return pkg.scripts || {};
}

function loadRoutes() {
  // route handler module names under server/routes/, plus inline endpoints in server.js
  const dir = path.join(ROOT, 'server', 'routes');
  let files = [];
  try { files = fs.readdirSync(dir).filter((f) => f.endsWith('.js')).map((f) => f.replace(/\.js$/, '')); } catch (_) {}
  files.sort();
  return { modules: files, inline: ['sources', 'health'] };
}

function computeFacts() {
  const { sources, listings } = loadData();
  const scripts = loadScripts();
  const routes = loadRoutes();

  const sourceKeys = Object.entries(sources)
    .map(([k, v]) => `${k}:${v.label || ''}:${v.tier || ''}`)
    .sort();
  const states = [...new Set(listings.map((l) => l.state).filter(Boolean))].sort();
  const propTypes = [...new Set(listings.map((l) => l.propType).filter(Boolean))].sort();
  const scriptsList = Object.entries(scripts).map(([k, v]) => `${k}=${v}`).sort();

  return {
    sourceCount: sourceKeys.length,
    sources: sourceKeys,
    listingCount: listings.length,
    states,
    propTypes,
    routeModules: routes.modules,
    inlineRoutes: routes.inline,
    scripts: scriptsList
  };
}

function computeDigest(facts) {
  return crypto.createHash('sha256').update(JSON.stringify(facts)).digest('hex');
}

function renderContext(facts) {
  const digest = computeDigest(facts);
  const src = facts.sources.map((s) => `- \`${s}\``).join('\n');
  return `# CONTEXT — property-crawl domain model

<!-- CONTEXT-DIGEST: ${digest} -->
> AUTO-GENERATED by \`node scripts/gen-context.js\`. Do not edit by hand.
> Regenerate after changing \`data.js\`, \`server/\` routes, or \`package.json\` scripts.
> Drift-gated by \`test/context.test.js\` and \`node scripts/gen-context.js --check\`.

## What this project is
"Zillow for distressed and government-sold property" — a discovery/triage layer over
sheriff sales, trustee sales, HUD/REO, IRS/Treasury/GSA dispositions.
Three layers: static PWA (v0, \`index.html\`/\`app.js\`), Node \`http\` listing API (v1,
\`server/\`), Next.js 16 App Router marketing site (v2, \`src/\`).

## Data shape (source of truth)
- \`SOURCES\`: ${facts.sourceCount} source types (key:label:tier)
${src}
- \`LISTINGS\`: ${facts.listingCount} records
- states: ${facts.states.join(', ')}
- property types: ${facts.propTypes.join(', ')}

## Server API routes
- modules: ${facts.routeModules.join(', ')}
- inline: ${facts.inlineRoutes.join(', ')}

## Commands
\`\`\`
${facts.scripts.map((s) => s).join('\n')}
\`\`\`

## Invariants (do not violate)
- Every dynamic/AI/user string renders through \`esc()\` / \`mdToHtml()\` (XSS invariant).
- \`SCORE_BANDS\` is the single source of truth for Deal Score color/label/alpha.
- Listing contract is camelCase (dealScore, openingBid, propType, ...); Postgres stores
  snake_case and \`server/db/client.js\` aliases back — production-only breakage risk.
`;
}

function main() {
  const args = process.argv.slice(2);
  const facts = computeFacts();
  const digest = computeDigest(facts);

  if (args.includes('--json')) {
    console.log(JSON.stringify({ facts, digest }, null, 2));
    return;
  }

  if (args.includes('--check')) {
    if (!fs.existsSync(CONTEXT_PATH)) {
      console.error('CONTEXT.md missing — run `node scripts/gen-context.js`');
      process.exit(1);
    }
    const existing = fs.readFileSync(CONTEXT_PATH, 'utf8');
    const m = existing.match(/CONTEXT-DIGEST:\s*([0-9a-f]{64})/);
    if (!m || m[1] !== digest) {
      console.error(`CONTEXT.md is STALE (digest ${m ? m[1].slice(0, 12) : 'MISSING'} != ${digest.slice(0, 12)}). Regenerate: node scripts/gen-context.js`);
      process.exit(1);
    }
    console.log('CONTEXT.md is current.');
    return;
  }

  fs.writeFileSync(CONTEXT_PATH, renderContext(facts));
  console.log(`Wrote ${CONTEXT_PATH} (${facts.sourceCount} sources, ${facts.listingCount} listings, ${facts.states.length} states)`);
}

module.exports = { computeFacts, computeDigest, renderContext, loadData, CONTEXT_PATH };

if (require.main === module) main();